# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20170613_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('home_team_id', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='usn',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_resource',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.User'),
        ),
        migrations.AlterField(
            model_name='user_team',
            name='team_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_team',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.User'),
        ),
    ]
