# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20170617_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='match_list',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='match_list',
            name='home_team_id',
        ),
        migrations.AddField(
            model_name='match_list',
            name='away_team',
            field=models.ForeignKey(default=12288, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='assignment.User_team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match_list',
            name='home_team',
            field=models.ForeignKey(default=12288, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='assignment.User_team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match_list',
            name='match_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match_list',
            name='match_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_resource',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.User'),
        ),
        migrations.AlterField(
            model_name='user_team',
            name='usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.User'),
        ),
    ]
